#!/usr/bin/env python3

"""
===============================================================================
 AES-256-GCM FILE ENCRYPTION + SHA-256 BENCHMARK
 Android / Termux Test Utility
===============================================================================

PURPOSE
-------

This script is intended primarily for benchmarking cryptographic operations
on an Android device running Python through Termux.

The script performs TWO separate cryptographic operations against an input
file:

    1. SHA-256 hashing
    2. AES-256-GCM encryption

The operations are deliberately performed separately.

This is important for benchmarking because it allows us to measure:

    - Time required to calculate SHA-256
    - SHA-256 throughput in MB/s

    - Time required to perform AES-256-GCM encryption
    - AES-256-GCM throughput in MB/s

    - Combined cryptographic processing time
    - Overall script runtime

Typical test files may include large MP4 video files generated for testing
mobile video-processing performance.

For example:

    200 MB MP4
    1 GB MP4
    5 GB MP4
    10 GB MP4

The script uses STREAMING I/O.

This means the complete file is NOT loaded into RAM.

Instead, the file is processed in relatively small chunks (currently 4 MB).

This is particularly important on Android devices where:

    - RAM is shared with the Android operating system
    - Applications operate within memory constraints
    - Video files may be several GB in size
    - Loading an entire video into memory would be impractical

-------------------------------------------------------------------------------
CRYPTOGRAPHIC OPERATIONS
-------------------------------------------------------------------------------

SHA-256:

    Python hashlib.sha256()

AES encryption:

    AES-256-GCM

AES key size:

    256 bits
    32 bytes

GCM nonce:

    96 bits
    12 bytes

GCM authentication tag:

    128 bits
    16 bytes

-------------------------------------------------------------------------------
ENCRYPTED FILE FORMAT
-------------------------------------------------------------------------------

The generated encrypted file has the following simple test format:

    +----------------------+
    | MAGIC HEADER         |
    +----------------------+
    | 96-bit NONCE         |
    +----------------------+
    | ENCRYPTED DATA       |
    | ...                  |
    | ...                  |
    +----------------------+
    | 128-bit GCM TAG      |
    +----------------------+

In byte form:

    MAGIC || NONCE || CIPHERTEXT || TAG

The MAGIC value allows software to identify files generated by this
particular test utility.

-------------------------------------------------------------------------------
IMPORTANT SECURITY NOTE
-------------------------------------------------------------------------------

A fresh random GCM nonce is generated for EVERY encryption operation.

Nonce reuse with the same AES-GCM key can catastrophically compromise the
security of AES-GCM.

Therefore:

    NEVER deliberately reuse a nonce with the same AES key.

os.urandom() is used to obtain cryptographically secure random bytes from
the operating system.

-------------------------------------------------------------------------------
ANDROID / TERMUX
-------------------------------------------------------------------------------

Typical installation:

    pkg update
    pkg install python
    pip install cryptography

Allow Termux access to Android shared storage:

    termux-setup-storage

Typical Android shared-storage locations exposed by Termux:

    ~/storage/downloads/
    ~/storage/shared/
    ~/storage/dcim/

Example execution:

    python aes_gcm_benchmark.py \
        ~/storage/downloads/video.mp4 \
        ~/storage/downloads/aes.key \
        ~/storage/downloads/video.mp4.enc

-------------------------------------------------------------------------------
AES KEY
-------------------------------------------------------------------------------

The key file must contain EXACTLY 32 RAW BYTES.

This represents:

    32 bytes × 8 bits = 256 bits

The key file is NOT expected to contain:

    - hexadecimal text
    - Base64 text
    - a password
    - a passphrase

It contains the actual raw AES key bytes.

Example key generation using Python:

    python -c "import os; open('aes.key','wb').write(os.urandom(32))"

===============================================================================
"""


# =============================================================================
# IMPORT STANDARD PYTHON MODULES
# =============================================================================

import os

# os provides operating-system functionality.
#
# We use it for:
#
#   - os.path.isfile()
#   - os.path.abspath()
#   - os.path.getsize()
#   - os.urandom()
#
# Of particular importance:
#
#   os.urandom()
#
# provides cryptographically secure random bytes obtained from the operating
# system. We use this to generate the AES-GCM nonce.


import sys

# sys provides access to command-line arguments.
#
# For example:
#
#   python aes_gcm_benchmark.py video.mp4 aes.key video.enc
#
# becomes:
#
#   sys.argv[0] = aes_gcm_benchmark.py
#   sys.argv[1] = video.mp4
#   sys.argv[2] = aes.key
#   sys.argv[3] = video.enc


import time

# time is used for benchmark timing.
#
# We use:
#
#   time.perf_counter()
#
# rather than wall-clock time.
#
# perf_counter() provides a high-resolution monotonic performance counter
# suitable for measuring elapsed execution time.


import hashlib

# hashlib provides Python's standard cryptographic hashing functions.
#
# We specifically use:
#
#   hashlib.sha256()
#
# to calculate the SHA-256 digest of the original input file.


# =============================================================================
# IMPORT CRYPTOGRAPHY LIBRARY
# =============================================================================

from cryptography.hazmat.primitives.ciphers import (
    Cipher,
    algorithms,
    modes
)

# Cipher
# ------
#
# Provides the cryptographic cipher interface.
#
#
# algorithms.AES
# --------------
#
# Selects the AES block cipher.
#
# Because our supplied key is 32 bytes / 256 bits, the cryptography library
# will use AES-256.
#
#
# modes.GCM
# ---------
#
# Selects Galois/Counter Mode.
#
# GCM provides both:
#
#   CONFIDENTIALITY
#
#       The file contents are encrypted.
#
#   AUTHENTICATION / INTEGRITY
#
#       Modification of ciphertext can be detected using the authentication
#       tag.
#
# This combination is known as:
#
#       AEAD
#
#       Authenticated Encryption with Associated Data.


# =============================================================================
# CONFIGURATION CONSTANTS
# =============================================================================


CHUNK_SIZE = 4 * 1024 * 1024

# File processing chunk size.
#
# 4 × 1024 × 1024 bytes
#
# = 4,194,304 bytes
# = 4 MiB
#
# Instead of loading an entire multi-GB MP4 into memory, we repeatedly read
# 4 MB blocks.
#
# Conceptually:
#
#       FILE
#        |
#        v
#    +--------+
#    | 4 MB   |
#    +--------+
#        |
#        v
#     process
#        |
#        v
#    +--------+
#    | 4 MB   |
#    +--------+
#        |
#       ...
#
# This keeps memory consumption approximately constant regardless of whether
# the input file is:
#
#       100 MB
#       1 GB
#       10 GB
#       50 GB
#
# Android note:
#
# Chunk size can influence benchmark results because storage I/O, Python
# overhead and filesystem caching all contribute to observed performance.


NONCE_SIZE = 12

# AES-GCM nonce size.
#
# 12 bytes
#
# = 96 bits
#
# 96 bits is the conventional/recommended nonce length for GCM.
#
# A NEW RANDOM NONCE MUST BE GENERATED FOR EACH ENCRYPTION OPERATION.


TAG_SIZE = 16

# GCM authentication tag size.
#
# 16 bytes
#
# = 128 bits
#
# The authentication tag allows a decryptor to verify that the ciphertext
# has not been modified.
#
# NOTE:
#
# TAG_SIZE is documented here primarily for understanding the output format.
# The cryptography library produces the GCM tag from encryptor.tag.


KEY_SIZE = 32

# AES key size.
#
# 32 bytes
#
# 32 × 8 = 256 bits
#
# Therefore:
#
#       AES-256


MAGIC = b"AES256GCM01"

# Simple file-format identifier.
#
# This is NOT a cryptographic value.
#
# It simply provides a recognizable header indicating that the encrypted
# file was produced using this utility.
#
# Current value:
#
#       AES256GCM01
#
# Length:
#
#       11 bytes


# =============================================================================
# HUMAN-READABLE FILE SIZE FUNCTION
# =============================================================================

def format_size(num_bytes):
    """
    Convert a byte count into a human-readable representation.

    Example:

        1024        -> 1.00 KB
        1048576     -> 1.00 MB
        1073741824  -> 1.00 GB

    This function is used only for reporting.

    It has no effect on encryption or hashing.
    """

    units = ["B", "KB", "MB", "GB", "TB"]

    # Convert integer byte count into floating point so division produces
    # convenient decimal output.
    size = float(num_bytes)

    # Progressively divide by 1024 until the most appropriate unit is found.
    for unit in units:

        if size < 1024:
            return f"{size:.2f} {unit}"

        size /= 1024

    # Extremely large files beyond TB are reported as PB.
    return f"{size:.2f} PB"


# =============================================================================
# SHA-256 FUNCTION
# =============================================================================

def calculate_sha256(filename):
    """
    Calculate the SHA-256 hash of a file.

    IMPORTANT:

    The file is processed using STREAMING I/O.

    We DO NOT do this:

        data = open(filename, "rb").read()

    because that could attempt to load an entire multi-gigabyte MP4 into RAM.

    Instead:

        read 4 MB
            |
            v
        SHA-256 update
            |
            v
        read next 4 MB
            |
            v
        SHA-256 update
            |
           ...

    The resulting SHA-256 digest is identical regardless of chunk size.

    Returns:

        digest
            SHA-256 digest represented as hexadecimal text.

        elapsed_time
            Number of seconds required to hash the complete file.
    """

    print()
    print("      [SHA-256] Initializing SHA-256 context...")

    # Create a new SHA-256 hashing object.
    sha256 = hashlib.sha256()

    print(f"      [SHA-256] Opening input file: {filename}")
    print(
        f"      [SHA-256] Processing file in "
        f"{CHUNK_SIZE // (1024 * 1024)} MB chunks..."
    )

    # Record benchmark start time immediately before file processing.
    start_time = time.perf_counter()

    # Open input file in binary mode.
    #
    # Binary mode is essential because MP4 and other files must be processed
    # byte-for-byte without text encoding or newline translation.
    with open(filename, "rb") as f:

        chunk_number = 0
        bytes_processed = 0

        while True:

            # Read up to CHUNK_SIZE bytes from the input file.
            chunk = f.read(CHUNK_SIZE)

            # An empty byte string indicates EOF.
            if not chunk:
                break

            # Feed this block into the SHA-256 state.
            sha256.update(chunk)

            chunk_number += 1
            bytes_processed += len(chunk)

    # Calculate total elapsed hashing time.
    elapsed_time = time.perf_counter() - start_time

    print(
        f"      [SHA-256] Processed {chunk_number:,} chunks."
    )

    print(
        f"      [SHA-256] Processed {format_size(bytes_processed)}."
    )

    print(
        f"      [SHA-256] Hash calculation completed in "
        f"{elapsed_time:.6f} seconds."
    )

    # Convert the binary 32-byte SHA-256 digest into the familiar
    # 64-character hexadecimal representation.
    digest = sha256.hexdigest()

    return digest, elapsed_time


# =============================================================================
# AES-256-GCM ENCRYPTION FUNCTION
# =============================================================================

def encrypt_aes256_gcm(input_file, output_file, key):
    """
    Encrypt a file using AES-256-GCM.

    INPUT:

        input_file

            Original file to encrypt.

            Example:

                video.mp4


        output_file

            Destination encrypted file.

            Example:

                video.mp4.enc


        key

            Raw 32-byte AES key.


    OUTPUT FILE STRUCTURE:

        +-----------------------------+
        | MAGIC                       |
        | "AES256GCM01"               |
        +-----------------------------+
        | NONCE                       |
        | 12 bytes / 96 bits          |
        +-----------------------------+
        |                             |
        | AES-GCM CIPHERTEXT          |
        |                             |
        | Variable length             |
        |                             |
        +-----------------------------+
        | GCM AUTHENTICATION TAG      |
        | 16 bytes / 128 bits         |
        +-----------------------------+


    IMPORTANT:

    Although the file is READ in chunks, this implementation represents ONE
    AES-GCM cryptographic message.

    In other words, it does NOT create an independent GCM nonce/tag for every
    4 MB chunk.

    Instead:

        ONE key
        ONE nonce
        ONE GCM encryption context
        ONE final authentication tag

    are used for the complete file.

    Chunking here is primarily an I/O and memory-management technique.
    """

    print()
    print("      [AES-GCM] Generating fresh 96-bit GCM nonce...")

    # Generate 12 cryptographically random bytes.
    #
    # A fresh nonce is generated every time this function executes.
    nonce = os.urandom(NONCE_SIZE)

    print(
        f"      [AES-GCM] Nonce generated: {nonce.hex()}"
    )

    print("      [AES-GCM] Creating AES-256 cipher context...")

    # Construct AES + GCM.
    #
    # Because 'key' is exactly 32 bytes, algorithms.AES(key) selects AES-256.
    #
    # modes.GCM(nonce) configures Galois/Counter Mode using our fresh nonce.
    cipher = Cipher(
        algorithms.AES(key),
        modes.GCM(nonce)
    )

    # Create an encryption context.
    #
    # The context maintains the internal GCM state while successive chunks
    # are encrypted.
    encryptor = cipher.encryptor()

    print("      [AES-GCM] AES-256-GCM context initialized.")

    print(
        f"      [AES-GCM] Input  : {input_file}"
    )

    print(
        f"      [AES-GCM] Output : {output_file}"
    )

    print(
        f"      [AES-GCM] Chunk size: "
        f"{CHUNK_SIZE // (1024 * 1024)} MB"
    )

    # Start timing immediately before performing file I/O and encryption.
    #
    # Therefore the measured encryption time includes:
    #
    #       reading input file
    #       AES-GCM processing
    #       writing ciphertext
    #       writing header/tag
    #
    # This is an END-TO-END encryption throughput measurement rather than a
    # pure AES primitive benchmark.
    start_time = time.perf_counter()

    # Open:
    #
    #   input file  -> binary read
    #   output file -> binary write
    #
    with open(input_file, "rb") as infile, \
         open(output_file, "wb") as outfile:

        # ---------------------------------------------------------------------
        # WRITE MAGIC HEADER
        # ---------------------------------------------------------------------

        outfile.write(MAGIC)

        # ---------------------------------------------------------------------
        # WRITE GCM NONCE
        # ---------------------------------------------------------------------
        #
        # The nonce is not secret.
        #
        # It needs to be available during decryption, so storing it alongside
        # the ciphertext is normal.
        #
        outfile.write(nonce)

        chunk_number = 0
        bytes_processed = 0

        # ---------------------------------------------------------------------
        # STREAM FILE THROUGH AES-GCM
        # ---------------------------------------------------------------------

        while True:

            # Read next 4 MB block.
            chunk = infile.read(CHUNK_SIZE)

            # EOF reached.
            if not chunk:
                break

            # Encrypt this portion of plaintext.
            #
            # GCM state is maintained internally by 'encryptor'.
            encrypted_chunk = encryptor.update(chunk)

            # Immediately write encrypted bytes to disk.
            #
            # This prevents ciphertext from accumulating in RAM.
            outfile.write(encrypted_chunk)

            chunk_number += 1
            bytes_processed += len(chunk)

        print(
            f"      [AES-GCM] Processed {chunk_number:,} chunks."
        )

        print(
            f"      [AES-GCM] Processed {format_size(bytes_processed)}."
        )

        print("      [AES-GCM] Finalizing encryption context...")

        # Finalize the GCM operation.
        #
        # After this call, encryptor.tag becomes available.
        encryptor.finalize()

        # ---------------------------------------------------------------------
        # WRITE GCM AUTHENTICATION TAG
        # ---------------------------------------------------------------------
        #
        # This tag is required during decryption.
        #
        # A decryptor uses the tag to verify ciphertext integrity and
        # authenticity.
        #
        outfile.write(encryptor.tag)

    # End benchmark timing after the output file has been written.
    elapsed_time = time.perf_counter() - start_time

    print(
        f"      [AES-GCM] Authentication tag: "
        f"{encryptor.tag.hex()}"
    )

    print(
        f"      [AES-GCM] Encryption completed in "
        f"{elapsed_time:.6f} seconds."
    )

    return nonce, encryptor.tag, elapsed_time


# =============================================================================
# AES KEY LOADING FUNCTION
# =============================================================================

def load_key(key_file):
    """
    Load the raw AES-256 key.

    AES-256 requires:

        256 bits

    Since:

        8 bits = 1 byte

    therefore:

        256 / 8 = 32 bytes

    The supplied key file MUST therefore contain exactly 32 bytes.

    Examples of INVALID key files:

        "MyPassword123"

        64 ASCII hexadecimal characters

        Base64 text

    This program expects the ACTUAL binary key bytes.
    """

    print()
    print(f"[KEY] Loading AES key from: {key_file}")

    # Read complete key file.
    #
    # Since the expected file is only 32 bytes, there is no need for
    # streaming here.
    with open(key_file, "rb") as f:
        key = f.read()

    print(
        f"[KEY] Key file contains {len(key)} bytes."
    )

    # Validate key length.
    if len(key) != KEY_SIZE:

        print()
        print("=" * 70)
        print("ERROR: INVALID AES KEY")
        print("=" * 70)

        print()
        print("AES-256 requires exactly 32 raw key bytes.")
        print()
        print(f"Expected : {KEY_SIZE} bytes")
        print(f"Received : {len(key)} bytes")
        print()

        sys.exit(1)

    print("[KEY] AES-256 key length validated successfully.")
    print("[KEY] Key material will NOT be displayed.")

    return key


# =============================================================================
# MAIN PROGRAM
# =============================================================================

def main():

    # -------------------------------------------------------------------------
    # COMMAND-LINE ARGUMENT VALIDATION
    # -------------------------------------------------------------------------

    # Expected:
    #
    #   argv[0] script
    #   argv[1] input file
    #   argv[2] key file
    #   argv[3] output file
    #
    # Therefore len(sys.argv) must equal 4.
    #
    if len(sys.argv) != 4:

        print()
        print("=" * 70)
        print("AES-256-GCM ENCRYPTION + SHA-256 BENCHMARK")
        print("ANDROID / TERMUX")
        print("=" * 70)

        print()
        print("Usage:")
        print()

        print(
            "  python aes_gcm_benchmark.py "
            "<input_file> <key_file> <output_file>"
        )

        print()
        print("Example:")
        print()

        print(
            "  python aes_gcm_benchmark.py "
            "~/storage/downloads/video.mp4 "
            "~/storage/downloads/aes.key "
            "~/storage/downloads/video.mp4.enc"
        )

        print()
        print("Required Python package:")
        print()
        print("  pip install cryptography")

        print()
        print("Termux shared-storage setup:")
        print()
        print("  termux-setup-storage")

        print()

        sys.exit(1)


    # -------------------------------------------------------------------------
    # GET COMMAND-LINE PARAMETERS
    # -------------------------------------------------------------------------

    input_file = sys.argv[1]
    key_file = sys.argv[2]
    output_file = sys.argv[3]


    # -------------------------------------------------------------------------
    # VERIFY INPUT FILE
    # -------------------------------------------------------------------------

    if not os.path.isfile(input_file):

        print()
        print(f"ERROR: Input file not found:")
        print(f"       {input_file}")
        print()

        sys.exit(1)


    # -------------------------------------------------------------------------
    # VERIFY KEY FILE
    # -------------------------------------------------------------------------

    if not os.path.isfile(key_file):

        print()
        print(f"ERROR: AES key file not found:")
        print(f"       {key_file}")
        print()

        sys.exit(1)


    # -------------------------------------------------------------------------
    # PREVENT ACCIDENTAL INPUT DESTRUCTION
    # -------------------------------------------------------------------------

    # If input_file and output_file point to the same path, opening the output
    # file for writing would truncate the original file.
    #
    # Therefore this condition is explicitly prohibited.
    #
    if os.path.abspath(input_file) == os.path.abspath(output_file):

        print()
        print("ERROR: Input and output files cannot be the same.")
        print()
        print("This protection prevents accidental destruction of")
        print("the original input file.")
        print()

        sys.exit(1)


    # -------------------------------------------------------------------------
    # LOAD AES KEY
    # -------------------------------------------------------------------------

    key = load_key(key_file)


    # -------------------------------------------------------------------------
    # DETERMINE INPUT FILE SIZE
    # -------------------------------------------------------------------------

    file_size = os.path.getsize(input_file)

    # MB value used for throughput calculation.
    #
    # Technically this is MiB because we divide by 1024 × 1024.
    #
    # It is labelled MB here for convenient benchmark reporting.
    file_size_mb = file_size / (1024 * 1024)


    # -------------------------------------------------------------------------
    # DISPLAY TEST INFORMATION
    # -------------------------------------------------------------------------

    print()
    print("=" * 70)
    print("AES-256-GCM + SHA-256 ANDROID BENCHMARK")
    print("=" * 70)

    print()
    print("TEST CONFIGURATION")
    print("-" * 70)

    print(f"Input file      : {input_file}")
    print(f"Input size      : {format_size(file_size)}")
    print(f"Input bytes     : {file_size:,}")
    print(f"Key file        : {key_file}")
    print(f"Output file     : {output_file}")

    print()
    print("CRYPTOGRAPHIC CONFIGURATION")
    print("-" * 70)

    print("AES algorithm   : AES-256")
    print("AES mode        : GCM")
    print("AES key size    : 256 bits / 32 bytes")
    print("GCM nonce size  : 96 bits / 12 bytes")
    print("GCM tag size    : 128 bits / 16 bytes")
    print("Hash algorithm  : SHA-256")

    print()
    print("I/O CONFIGURATION")
    print("-" * 70)

    print(
        f"Chunk size      : "
        f"{CHUNK_SIZE // (1024 * 1024)} MB"
    )

    print()
    print("IMPORTANT BENCHMARK NOTE")
    print("-" * 70)

    print(
        "Reported times include Android storage I/O."
    )

    print(
        "Therefore these results represent practical end-to-end"
    )

    print(
        "file-processing performance, not pure AES/SHA CPU performance."
    )


    # -------------------------------------------------------------------------
    # START TOTAL BENCHMARK TIMER
    # -------------------------------------------------------------------------

    total_start = time.perf_counter()


    # =========================================================================
    # TEST 1: SHA-256
    # =========================================================================

    print()
    print("=" * 70)
    print("[1/2] SHA-256 HASH BENCHMARK")
    print("=" * 70)

    sha256_digest, hash_time = calculate_sha256(input_file)


    # Calculate SHA throughput.
    #
    # Example:
    #
    #   1000 MB file / 2 seconds
    #
    #       = 500 MB/s
    #
    if hash_time > 0:
        hash_speed = file_size_mb / hash_time
    else:
        hash_speed = 0

    print()
    print("      SHA-256 operation complete.")


    # =========================================================================
    # TEST 2: AES-256-GCM
    # =========================================================================

    print()
    print("=" * 70)
    print("[2/2] AES-256-GCM ENCRYPTION BENCHMARK")
    print("=" * 70)

    nonce, tag, encryption_time = encrypt_aes256_gcm(
        input_file,
        output_file,
        key
    )


    # Calculate AES encryption throughput.
    if encryption_time > 0:
        encryption_speed = file_size_mb / encryption_time
    else:
        encryption_speed = 0

    print()
    print("      AES-256-GCM operation complete.")


    # -------------------------------------------------------------------------
    # STOP TOTAL BENCHMARK TIMER
    # -------------------------------------------------------------------------

    total_time = time.perf_counter() - total_start


    # -------------------------------------------------------------------------
    # GET FINAL ENCRYPTED FILE SIZE
    # -------------------------------------------------------------------------

    output_size = os.path.getsize(output_file)


    # =========================================================================
    # FINAL RESULTS
    # =========================================================================

    print()
    print("=" * 70)
    print("FINAL BENCHMARK RESULTS")
    print("=" * 70)


    # -------------------------------------------------------------------------
    # CRYPTOGRAPHIC INFORMATION
    # -------------------------------------------------------------------------

    print()
    print("CRYPTOGRAPHIC INFORMATION")
    print("-" * 70)

    print(f"Encryption      : AES-256-GCM")
    print(f"Key size        : 256 bits")
    print(f"Nonce size      : {NONCE_SIZE * 8} bits")
    print(f"Tag size        : {TAG_SIZE * 8} bits")

    # Nonce is not secret and may safely be reported.
    print(f"Nonce           : {nonce.hex()}")

    # Authentication tag is also not secret.
    print(f"GCM tag         : {tag.hex()}")


    # -------------------------------------------------------------------------
    # SHA-256 RESULTS
    # -------------------------------------------------------------------------

    print()
    print("SHA-256 RESULTS")
    print("-" * 70)

    print(f"SHA-256         : {sha256_digest}")
    print(f"Hash time       : {hash_time:.6f} seconds")
    print(f"Hash throughput : {hash_speed:.2f} MB/s")


    # -------------------------------------------------------------------------
    # AES RESULTS
    # -------------------------------------------------------------------------

    print()
    print("AES-256-GCM RESULTS")
    print("-" * 70)

    print(f"Encryption time : {encryption_time:.6f} seconds")
    print(f"AES throughput  : {encryption_speed:.2f} MB/s")


    # -------------------------------------------------------------------------
    # FILE INFORMATION
    # -------------------------------------------------------------------------

    print()
    print("FILE INFORMATION")
    print("-" * 70)

    print(f"Original size   : {format_size(file_size)}")
    print(f"Original bytes  : {file_size:,}")

    print(f"Encrypted size  : {format_size(output_size)}")
    print(f"Encrypted bytes : {output_size:,}")

    print(
        f"File overhead   : "
        f"{output_size - file_size:,} bytes"
    )


    # -------------------------------------------------------------------------
    # TIMING SUMMARY
    # -------------------------------------------------------------------------

    print()
    print("TIMING SUMMARY")
    print("-" * 70)

    print(
        f"SHA-256 time    : {hash_time:.6f} seconds"
    )

    print(
        f"AES-GCM time    : {encryption_time:.6f} seconds"
    )

    print(
        f"Combined crypto : "
        f"{hash_time + encryption_time:.6f} seconds"
    )

    print(
        f"Total runtime   : {total_time:.6f} seconds"
    )


    # -------------------------------------------------------------------------
    # THROUGHPUT SUMMARY
    # -------------------------------------------------------------------------

    print()
    print("THROUGHPUT SUMMARY")
    print("-" * 70)

    print(
        f"SHA-256         : {hash_speed:.2f} MB/s"
    )

    print(
        f"AES-256-GCM     : {encryption_speed:.2f} MB/s"
    )


    # -------------------------------------------------------------------------
    # SUCCESS
    # -------------------------------------------------------------------------

    print()
    print("=" * 70)
    print("BENCHMARK COMPLETED SUCCESSFULLY")
    print("=" * 70)

    print()
    print(f"Encrypted file:")
    print(f"  {output_file}")

    print()
    print("SHA-256 of original plaintext:")
    print(f"  {sha256_digest}")

    print()
    print("NOTE:")
    print(
        "  Keep the 32-byte AES key secure. The encrypted file cannot"
    )

    print(
        "  be recovered without the correct key."
    )

    print()


# =============================================================================
# PYTHON ENTRY POINT
# =============================================================================

# When the script is executed directly:
#
#     python aes_gcm_benchmark.py ...
#
# Python sets:
#
#     __name__ == "__main__"
#
# We then execute main().
#
# If this file were imported as a Python module, main() would NOT
# automatically execute.

if __name__ == "__main__":
    main()